<?php

namespace App\Http\Controllers\Shared;

use App\Http\Controllers\Controller;
use App\Models\RateLimiter;
use App\Services\Auth;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

/**
 * Ported from backend/Controllers/Shared/AiSuggestionController.php. Role
 * gating (employer/admin/superadmin) is applied at the route level via the
 * 'role' middleware, matching the original's Auth::requireAnyRole() call.
 */
class AiSuggestionController extends Controller
{
    private const FALLBACK = [
        'requirements' => [
            'Bachelor\'s degree in relevant field',
            '3+ years of experience in related role',
            'Proficiency in relevant tools/technologies',
            'Strong communication skills',
        ],
        'qualifications' => [
            'Experience with industry-standard software',
            'Ability to work in a team environment',
            'Strong problem-solving skills',
            'Relevant certifications preferred',
        ],
    ];

    public function jobSuggestions(Request $request): JsonResponse
    {
        if (!$request->isMethod('POST')) {
            return response()->json(['error' => 'Only POST requests are allowed'], 405);
        }

        $jobTitle = $request->input('jobTitle');
        $field = $request->input('field');

        if (!$jobTitle) {
            return response()->json(['error' => 'Job title is required'], 400);
        }

        if (!in_array($field, ['requirements', 'qualifications'], true)) {
            return response()->json(['error' => 'Invalid field specified'], 400);
        }

        // Each call spends a paid Gemini API request — rate limit per user so
        // a scripted loop against this endpoint can't burn through the key.
        $rateLimiter = new RateLimiter();
        $userId = (string) (Auth::user()['user_id'] ?? '');
        if ($rateLimiter->tooManyAttempts('ai_suggestions', $userId, 20, 60)) {
            return response()->json(['error' => 'Too many requests. Please slow down.'], 429);
        }
        $rateLimiter->hit('ai_suggestions', $userId);

        $apiKey = env('GEMINI_API_KEY');
        if (!$apiKey) {
            return response()->json(['error' => 'AI suggestions are not configured.'], 500);
        }

        $endpoint = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent?key='.$apiKey;
        $prompt = "Act as an HR manager. For a '{$jobTitle}' role, provide exactly 20 concise {$field} as a JSON array of strings. Return only the JSON array, e.g., [\"Item 1\", \"Item 2\"]. Ensure the output is valid JSON.";

        $payload = [
            'contents' => ['parts' => [['text' => $prompt]]],
            'generationConfig' => [
                'temperature' => 0.7,
                'maxOutputTokens' => 1000,
                'responseMimeType' => 'application/json',
            ],
        ];

        $ch = curl_init($endpoint);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_POST, true);
        curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($payload));
        curl_setopt($ch, CURLOPT_HTTPHEADER, ['Content-Type: application/json']);
        curl_setopt($ch, CURLOPT_TIMEOUT, 20);

        $response = curl_exec($ch);
        $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        curl_close($ch);

        if ($httpCode !== 200) {
            error_log("Gemini API Error (HTTP {$httpCode}): ".$response);

            return response()->json(['error' => 'API Error', 'details' => $response], $httpCode ?: 502);
        }

        $responseData = json_decode($response, true);
        if (json_last_error() !== JSON_ERROR_NONE) {
            error_log('Invalid JSON from Gemini API: '.$response);

            return response()->json(['error' => 'Invalid JSON from API', 'raw' => $response]);
        }

        $generatedText = $responseData['candidates'][0]['content']['parts'][0]['text'] ?? null;
        if (!$generatedText) {
            error_log('No text generated by Gemini API: '.json_encode($responseData));

            return response()->json(['error' => 'No text generated']);
        }

        $suggestions = json_decode($generatedText, true);
        if (json_last_error() !== JSON_ERROR_NONE) {
            error_log('Invalid JSON from AI: '.$generatedText);

            return response()->json([
                'success' => true,
                'suggestions' => self::FALLBACK[$field],
                'warning' => 'Used fallback suggestions due to invalid AI response',
            ]);
        }

        if (!is_array($suggestions)) {
            error_log('AI response is not an array: '.$generatedText);

            return response()->json(['error' => 'AI response is not a valid array', 'raw' => $generatedText]);
        }

        return response()->json(['success' => true, 'suggestions' => array_slice($suggestions, 0, 20)]);
    }
}
